version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.1-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
      - run:
          name: Install Composer Dependencies
          command: |
            composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - run:
          name: Build the App
          command: |
            php larakit app:build --build-version=1.0-ci-test -v
      - run:
          name: Move build to /usr/local/bin
          command: sudo mv ./builds/larakit /usr/local/bin/larakit
      - run:
          name: Install Laravel
          command: |
            composer global require laravel/installer
            export PATH="$PATH:$HOME/.config/composer/vendor/bin"
            cd ~/
            laravel new laravel-test
            cd laravel-test/
      - run:
          name: Test Installing Debugbar
          command: larakit install debugbar
      - run:
          name: Test Installing Ide-Helper
          command: larakit install idehelper
      - run:
          name: Test Installing Livewire
          command: larakit install livewire
